### ISSUE TITLE
希望能改进对gcc 4.8.1 c++11模式的支持

### ISSUE THREAD

**Issue by mosir** [avplayer/avhttp#10]
目前，如果使用gcc 4.8.1 缺省使用c++11模式的话，会出现类似：

> d:\mingw\include\avhttp\detail\error_codec.hpp|251|error: looser throw specifier for 'virtual const char\* avhttp::detail::error_category_impl::name() const'|
> d:\mingw\include\boost\system\error_code.hpp|191|error:   overriding 'virtual const char\* boost::system::error_category::name() const noexcept (true)'|
> d:\mingw\include\avhttp\detail\error_codec.hpp|371|error: looser throw specifier for 'virtual boost::system::error_condition avhttp::detail::error_category_impl::default_error_condition(int) const'|
> d:\mingw\include\boost\system\error_code.hpp|493|error:   overriding 'virtual boost::system::error_condition boost::system::error_category::default_error_condition(int) const noexcept (true)'|

这样的提示。

C++我不熟，搜了一下，有人解释了原因：
http://stackoverflow.com/questions/5269957/looser-throw-specifier-error-in-c

jack看能否改进之。改进后，avbot也可以解决同样的问题了;-)

**Comment by wyujie** [comment]
compiler problem. Using g++-4.8 solves it.
