### ISSUE TITLE
用VS2008 编译AVPlayer 用到avhttp 出错了

### ISSUE THREAD

**Issue by wangcheng02** [avplayer/avhttp#25]
> f:\2014项目\avplayer-1106\avplayer-master\libyk\youku_impl.cpp(44) : warning C4305: “return”: 从“int”到“bool”截断
> 1>c:\boost_1_50_0\include\boost-1_50\boost\algorithm\cxx11\copy_if.hpp(42) : error C2679: 二进制“=”: 没有找到接受“avhttp::cookies::iterator”类型的右操作数的运算符(或没有可接受的转换)
> 1>        d:\program files (x86)\microsoft visual studio 9.0\vc\include\iterator(31): 可能是“std::back_insert_iterator<_Container> &std::back_insert_iterator<_Container>::operator =(avhttp::cookies::const_reference)”
> 1>        with
> 1>        [
> 1>            _Container=avhttp::cookies
> 1>        ]
> 1>        d:\program files (x86)\microsoft visual studio 9.0\vc\include\iterator(55): 或       “std::back_insert_iterator<_Container> &std::back_insert_iterator<_Container>::operator =(const std::back_insert_iterator<_Container> &)”
> 1>        with
> 1>        [
> 1>            _Container=avhttp::cookies
> 1>        ]
> 1>        试图匹配参数列表“(std::back_insert_iterator<_Container>, avhttp::cookies::iterator)”时
> 1>        with
> 1>        [
> 1>            _Container=avhttp::cookies
> 1>        ]
> 1>        f:\2014项目\avplayer-1106\avplayer-master\third_party\avhttp\include\avhttp\cookie.hpp(726): 参见对正在编译的函数 模板 实例化“OutputIterator boost::algorithm::copy_ifavhttp::cookies::iterator,std::back_insert_iterator<_Container,boost::_bi::bind_t<R,F,L>>(InputIterator,InputIterator,OutputIterator,Predicate)”的引用
> 1>        with
> 1>        [
> 1>            OutputIterator=std::back_insert_iteratoravhttp::cookies,
> 1>            _Container=avhttp::cookies,
> 1>            R=bool,
> 1>            F=bool (__cdecl *)(const avhttp::cookies::http_cookie &,const avhttp::cookies &),
> 1>            L=boost::_bi::list2boost::arg<1,boost::reference_wrapperavhttp::cookies>,
> 1>            InputIterator=avhttp::cookies::iterator,
> 1>            Predicate=boost::_bi::bind_t<bool,bool (__cdecl *)(const avhttp::cookies::http_cookie &,const avhttp::cookies &),boost::_bi::list2<boost::arg<1>,boost::reference_wrapperavhttp::cookies>>
> 1>        ]

**Comment by micfan** [comment]
Need more VS2017 support & report
