### ISSUE TITLE
HttpStatusCode 302 support needed

### ISSUE THREAD

**Issue by micfan** [avplayer/avhttp#31]
Well, I am `open(url)`
``` cpp
  std::string repo_url = "https://github.com/cloudfoundry/bosh";
```
it says:
``` bash
./hello
Operation not supported on socket
102
0x103ce51f0
```
We need 302, 301 support now.

**Comment by whyb** [comment]
Dr said that if you want request https and not compiled OpenSSL, Just will throw exception.

**Comment by micfan** [comment]
Yeah, this old man lie to me!
OpenSSL should be supported by default. However, `avhttp` did not, what a pity.
I just add the compile flags to avoid this stupid case. Haha!

**Comment by microcai** [comment]
I am no old man....
