### ISSUE TITLE
编码 URL

### ISSUE THREAD

**Issue by 745275633** [avplayer/avhttp#46]
libcurl 中有
```
char *curl_easy_escape( CURL * curl , const char * string , int length );
```
可以编码字符串，avhttp 中有没有这样的函数

**Comment by whyb** [comment]
dr说有的。 avhttp::escape_string

**Comment by Jackarain** [comment]
@745275633 有的，avhttp::escape_string，找找

**Comment by microcai** [comment]
@745275633 有的。 avhttp::escape_string

**Comment by microcai** [comment]
@microcai 搞错了， 是 avhttp::detail::escape_string

**Comment by LovelornPig** [comment]
@745275633

**Comment by 745275633** [comment]
对，是 `avhttp::detail::escape_string`
