### ISSUE TITLE
下载完成仍然占用下载文件

### ISSUE THREAD

**Issue by lilucpp** [avplayer/avhttp#48]
版本：avhttp-v2.9.9/multi_download工程
现象描述：下载完成时，如果multi_download对象没有析构，会继续占用下载文件，导致其他进程无法操作下载文件。
不良解决方案：因为一些原因，multi_download对象不能简单设置为局部变量，依靠离开作用域使其析构。可new一个对象，不用时释放。

能否改成：在检测到下载完成时，不再独占下载文件？
谢谢。

**Comment by Jackarain** [comment]
https://github.com/avplayer/avhttp/blob/master/include/avhttp/impl/multi_download.ipp#L1670

**Comment by Jackarain** [comment]
在这里是有关闭文件操作的啊。

**Comment by lilucpp** [comment]
多谢回复。主版本里是有的。
原来我用的v2.9.9里没有reset操作。
