### ISSUE TITLE
请教multi_download如何设置数字证书路径？

### ISSUE THREAD

**Issue by Eggache666** [avplayer/avhttp#50]
我用例子multi_download.cpp测试，下载https路径的文件。设置不校验证书运行出错，改为校验证书。
linux下只设置：
avhttp::settings s;
s.check_certificate = true;
即可
但windows下运行报错'unknown state'，应该是没设置证书路径的缘故，但这个里面没找到设置路径的证书。请问该如何设置？

另外，我用libcurl测试，选择不验证证书，是可以正常执行的，不知道为何此库会返回异常：unknown state。
经测试，http_stream也存在这种情况，即启用SSL，但是不验证证书，返回unknown state

**Comment by Jackarain** [comment]
url 什么的提供一下？

**Comment by Eggache666** [comment]
这里不方便发地址。曾经发过一封邮件给你们，里面提供过地址
