### ISSUE TITLE
请教下，如何设置超时时间？avhttp库默认超时时间是多少？

### ISSUE THREAD

**Issue by Eggache666** [avplayer/avhttp#51]
如题。我在用avhttp::http_stream的open的接口时，有时候会卡在这里，我没有等待它超时结束(不知道多久)就用ctrl+c取消了执行，想重现再等待一次却很难再现这种情况。请问有没有设置等待超时的接口？

**Comment by tylk520** [comment]
请问解决没

**Comment by Eggache666** [comment]
avhttp没提供，可以使用其他的比如boost的timer

**Comment by micfan** [comment]
超时默认11秒， 代码参见 

https://github.com/avplayer/avhttp/blob/575bfe529a69f432cc365362f58af937639791ef/include/avhttp/settings.hpp#L284

```
	// 超时断开, 默认为11秒.
	int time_out;
```


https://github.com/avplayer/avhttp/blob/575bfe529a69f432cc365362f58af937639791ef/include/avhttp/settings.hpp#L255

``` cpp
static const int default_time_out = 11;
```
